// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHAI0i8Zk51Yk4upCrogC-E6sIiYbg9GE',
    appId: '1:583227993224:web:70355458ea61cd2171033d',
    messagingSenderId: '583227993224',
    projectId: 'anime-seiti-app-9cee1',
    authDomain: 'anime-seiti-app-9cee1.firebaseapp.com',
    storageBucket: 'anime-seiti-app-9cee1.firebasestorage.app',
    measurementId: 'G-1PYSXSPDV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6A9jOBA-WqVZpgXqzExjbqVBcx6Iei7w',
    appId: '1:583227993224:android:8b1318e406bdbab271033d',
    messagingSenderId: '583227993224',
    projectId: 'anime-seiti-app-9cee1',
    storageBucket: 'anime-seiti-app-9cee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTo-u-zrz4AjMRSVMJsTYZveK0VGZNWZM',
    appId: '1:583227993224:ios:64efcfac37d2c79071033d',
    messagingSenderId: '583227993224',
    projectId: 'anime-seiti-app-9cee1',
    storageBucket: 'anime-seiti-app-9cee1.firebasestorage.app',
    iosBundleId: 'com.example.animeSeiti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTo-u-zrz4AjMRSVMJsTYZveK0VGZNWZM',
    appId: '1:583227993224:ios:64efcfac37d2c79071033d',
    messagingSenderId: '583227993224',
    projectId: 'anime-seiti-app-9cee1',
    storageBucket: 'anime-seiti-app-9cee1.firebasestorage.app',
    iosBundleId: 'com.example.animeSeiti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHAI0i8Zk51Yk4upCrogC-E6sIiYbg9GE',
    appId: '1:583227993224:web:76cba47b46597f2071033d',
    messagingSenderId: '583227993224',
    projectId: 'anime-seiti-app-9cee1',
    authDomain: 'anime-seiti-app-9cee1.firebaseapp.com',
    storageBucket: 'anime-seiti-app-9cee1.firebasestorage.app',
    measurementId: 'G-E1CF0S82SN',
  );
}
